// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stores.Infrastructure.Context;

namespace Stores.Infrastructure.Migrations
{
    [DbContext(typeof(StorePackageContext))]
    [Migration("20190502075252_InitStoreTables")]
    partial class InitStoreTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stores.Domain.Models.StorePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Stores.Domain.Models.StoreProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long>("PackageId");

                    b.Property<long?>("PackageId1");

                    b.Property<string>("ProductType");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PackageId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Stores.Domain.Models.StoreProduct", b =>
                {
                    b.HasOne("Stores.Domain.Models.StorePackage")
                        .WithMany("Products")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stores.Domain.Models.StorePackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId1");
                });
#pragma warning restore 612, 618
        }
    }
}
